INSERT INTO roles (name) VALUES ('ADMIN')   ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('MANAGER') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('VIEWER')  ON CONFLICT (name) DO NOTHING;